#.travis.yml
#
#Travis is an online testing system designed to test code on each github commit.


language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  
# command to install dependencies
install: "pip install pexpect"

# command to run tests
script: test_all